# Generated by Django 5.2.1 on 2025-05-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_remove_application_cover_letter_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="website",
        ),
        migrations.RemoveField(
            model_name="job",
            name="location",
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(default="No description provided."),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FT", "Full Time"),
                    ("PT", "Part Time"),
                    ("IN", "Internship"),
                    ("CT", "Contract"),
                ],
                default="FT",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jobs.job"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
