# Generated by Django 5.2.1 on 2025-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_remove_company_website_remove_job_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary",
        ),
        migrations.AddField(
            model_name="application",
            name="applicant_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="applicant_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="job",
            name="location",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Internship", "Internship"),
                    ("Remote", "Remote"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
