# Generated by Django 5.2.1 on 2025-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_remove_application_applicant_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="applied_at",
            new_name="applied_on",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="applicant",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="company",
            name="description",
        ),
        migrations.AddField(
            model_name="application",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="resume",
            field=models.FileField(blank=True, null=True, upload_to="resumes/"),
        ),
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "Full-time"),
                    ("Part-time", "Part-time"),
                    ("Internship", "Internship"),
                    ("Contract", "Contract"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
