# Generated by Django 5.2.1 on 2025-06-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_applied_at_application_applied_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),  # <- add default here temporarily
        ),
    ]
